name: Use Multiple jobs to publish Quarkus app to Docker Hub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the repo in the runner
        uses: actions/checkout@v4

      - name: Setup java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Package the quarkus app
        run: mvn clean package

      - name: Upload the artifact file to GitHub Actions storage
        uses: actions/upload-artifact@v3
        with:
          name: quarkus-app
          path: target/*.jar

      - name: Upload the Dockerfile to GitHub Actions storage
        uses: actions/upload-artifact@v3
        with:
          name: Dockerfile
          path: .
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: jaap17/quarkus-app-hello-world
    steps:
      - name: Download the quarkus-app artifact
        uses: actions/download-artifact@v3
        with:
          name: quarkus-app

      - name: Download the dockerfile artifact
        uses: actions/download-artifact@v3
        with:
          name: Dockerfile

      - name: Set docker image tag env
        run: echo "DOCKER_TAG_VERSION=$(echo $GITHUB_RUN_NUMBER)" >> $GITHUB_ENV

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: List files in the current directory
        run: ls

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG_VERSION }}