  on:
    push:
      branches:
        - main
  jobs:
    unit_test:
      runs-on: [ubuntu-latest]
      steps:
        - name: Checkout to the repo in the runner
          uses: actions/checkout@v1

        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Build with Maven
          run: mvn package

        - name: Generate Jacoco Test Report
          run: mvn verify

        - name: Printing Directory structure
          run: ls -R target/surefire-reports

#        - name: Upload coverage report
#          uses: actions/upload-artifact@v3
#          with:
#            name: coverage-report
#            path: target/jacoco-report/jacoco.xml

        - name: Report
          uses: dorny/test-reporter@v1
          if: always()
          with:
            name: Maven Tests
            path: target/jacoco-report/jacoco.csv
            reporter: java-junit
            fail-on-error: true